version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: remarkidian-backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./backend/src:/app/src
    environment:
      - NODE_ENV=development
      - DB_PATH=/app/data/db/remarkidian.db
      - LOG_PATH=/app/data/logs
      - PORT=5000
    networks:
      - remarkidian-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: remarkidian-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - remarkidian-network
    restart: unless-stopped

volumes:
  remarkidian-data:
    driver: local

networks:
  remarkidian-network:
    driver: bridge
