version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remarkidian-app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./backend/src:/app/backend/src
    environment:
      - NODE_ENV=development
      - DB_PATH=/app/data/db/remarkidian.db
      - LOG_PATH=/app/data/logs
      - PORT=5000
    networks:
      - remarkidian-network
    restart: unless-stopped

volumes:
  remarkidian-data:
    driver: local

networks:
  remarkidian-network:
    driver: bridge
